name: Wake up Supabase

on:
  schedule:
    - cron: '0 9 */2 * *'
  workflow_dispatch:

jobs:
  ping-supabase:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to Supabase
        run: |
          curl -s -X GET "https://jvwzrlzemuvhwvshhuid.supabase.co/rest/v1/books?select=*&limit=1" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
